/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;
import javax.swing.*;
import java.sql.*;
import java.text.ParseException;
import javax.swing.event.*;
import java.text.SimpleDateFormat;  
import java.util.ArrayList;
import java.util.Date; 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Helena Bulati
 */
public class NewJFrame extends javax.swing.JFrame {
    public Connection conn = null;
    public Statement stmt;
    public ResultSet rs;
    public ResultSet rs2;
    

    
 



    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        abas.setEnabledAt(1, false);
        abas.setEnabledAt(2, false);
        populateTable();
    }
    
    public void populateTable() {
        
        Integer d;
        String e; 
        String f; 
        String g;
        Integer h;
        String j;
        String k;
        String l;
        String m;
        ArrayList<ArrayList<String>> dataArr = new ArrayList<>();
        try { Class.forName("com.mysql.cj.jdbc.Driver");
            
            PreparedStatement ps = null;
           
            
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost/novoprojetodb", "root","123");
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            
            String sql="SELECT IDanimal, especies.Especie, NomePet, Nascimento, IDtutor, "
                    + "Nome, Email, Telefone1, Telefone2 FROM animais INNER JOIN tutores ON animais.Tutor = "
                    + "tutores.IDtutor INNER JOIN especies WHERE animais.Especie = especies.ID;";
            ps = conn.prepareStatement(sql);
            ResultSet rs2 = ps.executeQuery(sql);
            
            //String data[][];
            
            while(rs2.next()){
            
                d = rs2.getInt("IDanimal");
                e = rs2.getString("Especie");
                f = rs2.getString("NomePet");
                g = rs2.getString("Nascimento");
                h = rs2.getInt("IDTutor");
                j = rs2.getString("Nome");
                k = rs2.getString("Email");
                l = rs2.getString("Telefone1");
                m = rs2.getString("Telefone2");
                
                String dstr = d.toString();
                String hstr = h.toString();
                ArrayList<String> cars = new ArrayList<String>();
                cars.add(dstr);
                cars.add(e);
                cars.add(f);
                cars.add(g);
                cars.add(hstr);
                cars.add(j);
                cars.add(k);
                cars.add(l);
                cars.add(m);
                dataArr.add(cars);
                //model.addRow(new Object[]{d, e, f, g, h, j, k, l, m});
            }
            
        }catch (Exception ee) {
            System.out.println(ee.getMessage());
        }
        
        String columns[] = {"ID Animal","Espécie","Nome Pet","Nascimento","ID Tutor","Nome do Tutor","E-mail","Telefone1","Telefone2"};
        
        String[][] data = dataArr.stream().map(u -> u.toArray(new String[0])).toArray(String[][]::new);
        //String[][] data = dataArr.toArray(new String[0]);

        DefaultTableModel model = new DefaultTableModel(data,columns);
        jTable1.setModel(model);
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtlogin = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        nometutor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nomepet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaespecie = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btncadastrar = new javax.swing.JButton();
        datanascMes = new javax.swing.JTextField();
        datanascAno = new javax.swing.JTextField();
        datanascDia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telefone1txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        telefone2txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        atualizartable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginActionPerformed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtlogin)
                                .addComponent(txtsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3)))))
                .addContainerGap(749, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        abas.addTab("Login", jPanel1);

        jScrollPane3.setHorizontalScrollBar(null);

        nometutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometutorActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome do tutor");

        nomepet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomepetActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome do animal");

        listaespecie.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "----------", "Cachorro", "Gato", "Papagaio", "Coelho", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaespecie.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaespecieValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaespecie);

        jLabel6.setText("Espécie do animal");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel7.setText("Cadastro de Pacientes");

        jLabel8.setText("Data de nascimento do animal");

        btncadastrar.setText("Cadastrar");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        datanascMes.setText("Mês");
        datanascMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datanascMesActionPerformed(evt);
            }
        });

        datanascAno.setText("Ano");
        datanascAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datanascAnoActionPerformed(evt);
            }
        });

        datanascDia.setText("Dia");
        datanascDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datanascDiaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel1.setText("Dados do tutor");

        jLabel9.setText("E-mail");

        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });

        jLabel10.setText(" Telefone 1");

        telefone1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone1txtActionPerformed(evt);
            }
        });

        jLabel11.setText("Telefone 2");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel12.setText("Dados do animal");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nomepet, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(telefone2txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(telefone1txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emailtxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nometutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btncadastrar)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(datanascDia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(datanascMes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datanascAno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nometutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefone1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefone2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomepet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datanascMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datanascAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datanascDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btncadastrar)
                .addGap(38, 38, 38))
        );

        jScrollPane3.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        abas.addTab("Cad. Pacientes", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Animal", "ID Tutor", "Nome Animal", "Nome Tutor", "Espécie", "Data de Nascimento", "E-mail", "Telefone 1", "Telefone 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        atualizartable.setText("Atualizar");
        atualizartable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizartableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atualizartable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atualizartable)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        abas.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // explicação: o campo senha não gera uma string, portanto aqui estamos convertendo ela pra string
        String senha = new String(txtsenha.getPassword());
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/novoprojetodb",
                    "root", "123");
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT COUNT(*) FROM login WHERE user = '"
                    + txtlogin.getText() + "' AND senha = '"
                    + txtsenha.getText() + "';";
            //ESTE CÓDIGO MOSTRA O CÓDIGO SQL EXECUTADO (pra fins de verificar o que vc tá mandando pro console)
            //JOptionPane.showMessageDialog(null, sql);
            
            
            rs = stmt.executeQuery(sql);
            while (rs.next() == true) {
                
                //System.out.println("esta true");
                int n = 0;
                n = rs.getInt(1);
                
                if ( n > 0 ) {
                // do what ever you need, if the row exists  
                JOptionPane.showMessageDialog(null, "Login efetuado com sucesso.");
                abas.setEnabledAt(1, true);
                abas.setEnabledAt(2, true);
                abas.setSelectedIndex(1);
                }
                else {
                    JOptionPane.showMessageDialog(null,
                        "Dados de Login incorretos.",
                        "Mensagem", JOptionPane.INFORMATION_MESSAGE
                    );
                }
                
            }
            
            
        } catch (ClassNotFoundException e) {
            System.out.println(e);
        } catch (SQLException e) {
            System.out.println(e);
        }
                        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloginActionPerformed

    private void nometutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometutorActionPerformed

    private void nomepetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomepetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomepetActionPerformed

    private void listaespecieValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaespecieValueChanged
        // TODO add your handling code here:
        

        int selectedValues[] = listaespecie.getSelectedIndices();
        //System.out.println(selectedValues[0]);
        int selecionado = selectedValues[0];
        //System.out.println(selecionado);
        
    }//GEN-LAST:event_listaespecieValueChanged

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        // TODO add your handling code here:
        
        
        int selecionado = 0;
         
        //nometutor, nomepet, datanasc, selecionado
        try {
            int selectedValues[] = listaespecie.getSelectedIndices();
        
            selecionado = selectedValues[0];
        } catch (Exception exp) {
            //System.out.println("Selecionar espécie.");
            //JOptionPane.showMessageDialog(null,
                        //"Por favor, selecione a espécie do animal.",
                       // "Mensagem de erro", JOptionPane.INFORMATION_MESSAGE
                    //);
        }
        
        if (selecionado > 0){
            
            
            
            String data1 = datanascAno.getText() + "-" + datanascDia.getText() + "-" + datanascMes.getText();
            String data2 = data1;
            //System.out.println(data2);

            //below is an attempt where i used the date data type on mysql 
            // try {
            //   this.date1 = formatter.parse(data2);
            //}catch (ParseException e) {
            //          }finally {
            //}
            //System.out.println(date1);
            //java.sql.Date sqlDate = new java.sql.Date(date1.getTime());
            //System.out.println(sqlDate);
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");

                //conn = DriverManager.getConnection("jdbc:mysql://localhost/novoprojetodb",
                //   "root", "123");
                PreparedStatement ps = null;
                PreparedStatement ps1 = null;
                PreparedStatement ps2 = null;
                PreparedStatement ps3 = null;
                PreparedStatement ps4 = null;

                stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                        ResultSet.CONCUR_UPDATABLE);
                conn = DriverManager.getConnection("jdbc:mysql://localhost/novoprojetodb", "root", "123");

                int i = 0;
                int ii = 0;
                int iTutor = 0;
                //i = stmt.executeUpdate(sql);//executando o comando sql
                //stmt.close();

                String query = "INSERT INTO animais(NomePet,Especie,Nascimento) VALUES(?,?,?);";

                // + " INSERT INTO tutores (Nome) VALUES ('"
                //+ nometutor.getText() + "');";
                ps = conn.prepareStatement(query);
                ps.setString(1, nomepet.getText());
                ps.setInt(2, selecionado);
                ps.setString(3, data2);
                //System.out.println(query);
                i = ps.executeUpdate();

                String query1 = "INSERT INTO tutores (Nome,Email,Telefone1,Telefone2) VALUES (?,?,?,?);";
                ps1 = conn.prepareStatement(query1);
                ps1.setString(1, nometutor.getText());
                ps1.setString(2, emailtxt.getText());
                ps1.setString(3, telefone1txt.getText());
                ps1.setString(4, telefone2txt.getText());
                iTutor = ps1.executeUpdate();

                int idtut = 0;
                ResultSet rs2 = null;
                try {
                    String query2 = "SELECT IDtutor FROM tutores WHERE (Nome, Email, Telefone1, Telefone2) = ('"
                            + nometutor.getText() + "', "
                            + "'" + emailtxt.getText() + "', "
                            + "'" + telefone1txt.getText() + "', "
                            + "'" + telefone2txt.getText() + "');";
                    ps2 = conn.prepareStatement(query2);
                    //System.out.println(query2);
                    rs2 = ps2.executeQuery();
                    while (rs2.next()) {
                        idtut = rs2.getInt("IDtutor");
                        //System.out.println(idtut);
                    }
                } catch (SQLException e) {
                    // Print exception pop-up on screen
                    System.out.println(e);
                }

                int IDanimal = 0;
                ResultSet rs3 = null;
                try {
                    String query4 = "SELECT IDanimal FROM animais WHERE (NomePet,Especie,Nascimento) = ('"
                            + nomepet.getText() + "',"
                            + selecionado + "," + "'" + data2 + "');";
                    ps4 = conn.prepareStatement(query4);
                   //System.out.println(query4);
                    rs3 = ps4.executeQuery();
                    while (rs3.next()) {
                        IDanimal = rs3.getInt("IDanimal");
                        //System.out.println(IDanimal);
                    }
                } catch (SQLException e) {
                    // Print exception pop-up on screen
                    System.out.println(e);
                }
                //System.out.println(IDanimal);
                //System.out.println(idtut);
                //UPDATE animais SET Tutor = 19 WHERE IDanimal = 17;
                String query3 = "UPDATE animais SET Tutor = "
                        + idtut + " WHERE IDanimal = " + IDanimal + ";";
                ps3 = conn.prepareStatement(query3);
                //ps3.setInt(1, idtut);
                //System.out.println(query3);
                ii = ps3.executeUpdate();

                if (i > 0 && iTutor > 0 && ii > 0) {
                    JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");

                }
            } catch (ClassNotFoundException e) {
                System.out.println(e);
            } catch (SQLException e) {
                System.out.println(e);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("Selecionar espécie.");
            JOptionPane.showMessageDialog(null,
                        "Por favor, selecione a espécie do animal.",
                        "Mensagem de erro", JOptionPane.INFORMATION_MESSAGE
                    );
        }
        
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void datanascMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datanascMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datanascMesActionPerformed

    private void datanascAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datanascAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datanascAnoActionPerformed

    private void datanascDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datanascDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datanascDiaActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void telefone1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefone1txtActionPerformed

    private void atualizartableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizartableActionPerformed
        // TODO add your handling code here:
        populateTable();
        
    }//GEN-LAST:event_atualizartableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton atualizartable;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JTextField datanascAno;
    private javax.swing.JTextField datanascDia;
    private javax.swing.JTextField datanascMes;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listaespecie;
    private javax.swing.JTextField nomepet;
    private javax.swing.JTextField nometutor;
    private javax.swing.JTextField telefone1txt;
    private javax.swing.JTextField telefone2txt;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
